# Generated by Django 5.0.3 on 2024-03-16 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('House_number', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('House_Name', models.CharField(max_length=25)),
                ('B_H_K', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('Sq_ft', models.IntegerField()),
                ('Occupied', models.BooleanField()),
                ('Place', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
